name: Zbuduj Flet APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie kodu repozytorium
        uses: actions/checkout@v4

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Konfiguracja Java / Android SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalacja bibliotek i narzędzia Flet
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Budowanie APK dla Androida
        env:
          CI: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yes | flet build apk --project "ocrLmm" --description "Skaner PZ do EDI" -v

      - name: Zapisanie pliku APK jako Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ocrLmm-Android-APK
          path: build/apk/*.apk
