name: Zbuduj Flet APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie kodu repozytorium
        uses: actions/checkout@v4

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Użycie oficjalnego i stabilnego akceleratora budowania Fleta
      - name: Budowanie aplikacji przez Flet Build Action
        uses: flet-dev/build-app-action@v1
        with:
          target: main.py
          platforms: android

      - name: Zapisanie pliku APK jako Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ocrLmm-Android-APK
          path: build/apk/*.apk
